name: autofix.ci
on: [pull_request]

permissions:
  contents: read

jobs:
  lint:
    name: Autofix
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
        with:
          persist-credentials: false

      - name: Set up UV
        id: setup-uv
        uses: astral-sh/setup-uv@d31148d669074a8d0a63714ba94f3201e7020bc3 # v8.3.0
        with:
          enable-cache: false

      - name: Install dependencies
        run: uv sync --all-groups --all-extras

      - name: Run prek
        uses: j178/prek-action@e98a699c41eb69ab013a45817a0406469a748f8d # v2.0.5

      - name: Commits back to branch if necessary
        uses: autofix-ci/action@c5b2d67aa2274e7b5a18224e8171550871fc7e4a # v1.3.4
        if: failure()
